name: 'Infracost Comment'
description: 'Ejecuta Infracost y comenta en el PR'

inputs:
  path:
    description: 'Ruta del código Terraform'
    default: '.'
    required: false
  github_token:
    description: 'GITHUB_TOKEN para comentar en el PR'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Infracost diff
      shell: bash
      run: |
        infracost breakdown --path=${{ inputs.path }} \
                            --format=table