# .github/workflows/dev-pipeline.yml
name: Dev Pipeline
on:
  push:
    branches: [ develop ]

jobs:
  ci:
    uses: ./.github/workflows/terraform-ci.yml
    with:
      environment: dev
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}å
  
  cd:
    needs: ci
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: dev
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}å