


name: Reusable Apply

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      WEBHOOK_URL:
        required: true

jobs:
  apply:
    runs-on: ubuntu-latest

    environment: production

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: GCP Auth
        uses: ./.github/actions/authentication
        with:
          workload_identity_provider: projects/151708230233/locations/global/workloadIdentityPools/github-pool-pipe/providers/github-provider
          service_account: github-actions@sdg-hub-project.iam.gserviceaccount.com

      - uses: hashicorp/setup-terraform@v3

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=sdg-hub-tfstate" \
            -backend-config="prefix=terraform/state/${{ inputs.environment }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Notify
        uses: ./.github/actions/notification
        with:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          status: ${{ job.status }}
          message: "Terraform apply executed without errors in ${{ inputs.environment }} environment and commit ${{ github.sha }}"
        continue-on-error: true